name: CSV to JSON Converter

on:
  push:
    paths:
      - 'tefas.csv' # Sadece tefas.csv yüklendiğinde/değiştiğinde çalışır
  workflow_dispatch: # İstediğinde manuel çalıştırmak için

jobs:
  convert-job:
    runs-on: ubuntu-latest
    # Git push yetkisi için gerekli:
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pandas

      - name: Run Converter
        run: python convert.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Tefas Bot'
          git config --global user.email 'tefas-bot@github.com'
          git add yatirim_fonlari.json
          # Eğer değişiklik yoksa hata vermemesi için || true ekliyoruz
          git commit -m "Otomatik JSON Güncellemesi: $(date +'%d-%m-%Y %H:%M')" || true
          git push
