name: TEFAS Gunluk Guncelleme

on:
  schedule:
    - cron: '30 07 * * 1-5'
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  veri-cek-ve-kaydet:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Al
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: |
          pip install requests

      - name: TEFAS Botunu Çalıştır
        run: |
          rm -f yatirim_fonlari.json
          python tefas_bot.py
          [ -f yatirim_fonlari.json ] || (echo "HATA: Script yeni veri dosyasını oluşturamadı!" && exit 1)

      - name: Yeni Verileri GitHub'a Kaydet
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add yatirim_fonlari.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik Güncelleme: $(date +'%Y-%m-%d')" && git push)
